
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `CampaignMetric` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model CampaignMetric
 * 
 */
export type CampaignMetricModel = runtime.Types.Result.DefaultSelection<Prisma.$CampaignMetricPayload>

export type AggregateCampaignMetric = {
  _count: CampaignMetricCountAggregateOutputType | null
  _avg: CampaignMetricAvgAggregateOutputType | null
  _sum: CampaignMetricSumAggregateOutputType | null
  _min: CampaignMetricMinAggregateOutputType | null
  _max: CampaignMetricMaxAggregateOutputType | null
}

export type CampaignMetricAvgAggregateOutputType = {
  roas: number | null
}

export type CampaignMetricSumAggregateOutputType = {
  roas: number | null
}

export type CampaignMetricMinAggregateOutputType = {
  id: string | null
  campaignId: string | null
  roas: number | null
  recordedAt: Date | null
}

export type CampaignMetricMaxAggregateOutputType = {
  id: string | null
  campaignId: string | null
  roas: number | null
  recordedAt: Date | null
}

export type CampaignMetricCountAggregateOutputType = {
  id: number
  campaignId: number
  roas: number
  recordedAt: number
  _all: number
}


export type CampaignMetricAvgAggregateInputType = {
  roas?: true
}

export type CampaignMetricSumAggregateInputType = {
  roas?: true
}

export type CampaignMetricMinAggregateInputType = {
  id?: true
  campaignId?: true
  roas?: true
  recordedAt?: true
}

export type CampaignMetricMaxAggregateInputType = {
  id?: true
  campaignId?: true
  roas?: true
  recordedAt?: true
}

export type CampaignMetricCountAggregateInputType = {
  id?: true
  campaignId?: true
  roas?: true
  recordedAt?: true
  _all?: true
}

export type CampaignMetricAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which CampaignMetric to aggregate.
   */
  where?: Prisma.CampaignMetricWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of CampaignMetrics to fetch.
   */
  orderBy?: Prisma.CampaignMetricOrderByWithRelationInput | Prisma.CampaignMetricOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.CampaignMetricWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` CampaignMetrics from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` CampaignMetrics.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned CampaignMetrics
  **/
  _count?: true | CampaignMetricCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: CampaignMetricAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: CampaignMetricSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: CampaignMetricMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: CampaignMetricMaxAggregateInputType
}

export type GetCampaignMetricAggregateType<T extends CampaignMetricAggregateArgs> = {
      [P in keyof T & keyof AggregateCampaignMetric]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateCampaignMetric[P]>
    : Prisma.GetScalarType<T[P], AggregateCampaignMetric[P]>
}




export type CampaignMetricGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.CampaignMetricWhereInput
  orderBy?: Prisma.CampaignMetricOrderByWithAggregationInput | Prisma.CampaignMetricOrderByWithAggregationInput[]
  by: Prisma.CampaignMetricScalarFieldEnum[] | Prisma.CampaignMetricScalarFieldEnum
  having?: Prisma.CampaignMetricScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: CampaignMetricCountAggregateInputType | true
  _avg?: CampaignMetricAvgAggregateInputType
  _sum?: CampaignMetricSumAggregateInputType
  _min?: CampaignMetricMinAggregateInputType
  _max?: CampaignMetricMaxAggregateInputType
}

export type CampaignMetricGroupByOutputType = {
  id: string
  campaignId: string
  roas: number
  recordedAt: Date
  _count: CampaignMetricCountAggregateOutputType | null
  _avg: CampaignMetricAvgAggregateOutputType | null
  _sum: CampaignMetricSumAggregateOutputType | null
  _min: CampaignMetricMinAggregateOutputType | null
  _max: CampaignMetricMaxAggregateOutputType | null
}

export type GetCampaignMetricGroupByPayload<T extends CampaignMetricGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<CampaignMetricGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof CampaignMetricGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], CampaignMetricGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], CampaignMetricGroupByOutputType[P]>
      }
    >
  >



export type CampaignMetricWhereInput = {
  AND?: Prisma.CampaignMetricWhereInput | Prisma.CampaignMetricWhereInput[]
  OR?: Prisma.CampaignMetricWhereInput[]
  NOT?: Prisma.CampaignMetricWhereInput | Prisma.CampaignMetricWhereInput[]
  id?: Prisma.StringFilter<"CampaignMetric"> | string
  campaignId?: Prisma.StringFilter<"CampaignMetric"> | string
  roas?: Prisma.FloatFilter<"CampaignMetric"> | number
  recordedAt?: Prisma.DateTimeFilter<"CampaignMetric"> | Date | string
  campaign?: Prisma.XOR<Prisma.CampaignScalarRelationFilter, Prisma.CampaignWhereInput>
}

export type CampaignMetricOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  campaignId?: Prisma.SortOrder
  roas?: Prisma.SortOrder
  recordedAt?: Prisma.SortOrder
  campaign?: Prisma.CampaignOrderByWithRelationInput
}

export type CampaignMetricWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.CampaignMetricWhereInput | Prisma.CampaignMetricWhereInput[]
  OR?: Prisma.CampaignMetricWhereInput[]
  NOT?: Prisma.CampaignMetricWhereInput | Prisma.CampaignMetricWhereInput[]
  campaignId?: Prisma.StringFilter<"CampaignMetric"> | string
  roas?: Prisma.FloatFilter<"CampaignMetric"> | number
  recordedAt?: Prisma.DateTimeFilter<"CampaignMetric"> | Date | string
  campaign?: Prisma.XOR<Prisma.CampaignScalarRelationFilter, Prisma.CampaignWhereInput>
}, "id">

export type CampaignMetricOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  campaignId?: Prisma.SortOrder
  roas?: Prisma.SortOrder
  recordedAt?: Prisma.SortOrder
  _count?: Prisma.CampaignMetricCountOrderByAggregateInput
  _avg?: Prisma.CampaignMetricAvgOrderByAggregateInput
  _max?: Prisma.CampaignMetricMaxOrderByAggregateInput
  _min?: Prisma.CampaignMetricMinOrderByAggregateInput
  _sum?: Prisma.CampaignMetricSumOrderByAggregateInput
}

export type CampaignMetricScalarWhereWithAggregatesInput = {
  AND?: Prisma.CampaignMetricScalarWhereWithAggregatesInput | Prisma.CampaignMetricScalarWhereWithAggregatesInput[]
  OR?: Prisma.CampaignMetricScalarWhereWithAggregatesInput[]
  NOT?: Prisma.CampaignMetricScalarWhereWithAggregatesInput | Prisma.CampaignMetricScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"CampaignMetric"> | string
  campaignId?: Prisma.StringWithAggregatesFilter<"CampaignMetric"> | string
  roas?: Prisma.FloatWithAggregatesFilter<"CampaignMetric"> | number
  recordedAt?: Prisma.DateTimeWithAggregatesFilter<"CampaignMetric"> | Date | string
}

export type CampaignMetricCreateInput = {
  id?: string
  roas: number
  recordedAt: Date | string
  campaign: Prisma.CampaignCreateNestedOneWithoutMetricsInput
}

export type CampaignMetricUncheckedCreateInput = {
  id?: string
  campaignId: string
  roas: number
  recordedAt: Date | string
}

export type CampaignMetricUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  roas?: Prisma.FloatFieldUpdateOperationsInput | number
  recordedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  campaign?: Prisma.CampaignUpdateOneRequiredWithoutMetricsNestedInput
}

export type CampaignMetricUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  campaignId?: Prisma.StringFieldUpdateOperationsInput | string
  roas?: Prisma.FloatFieldUpdateOperationsInput | number
  recordedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type CampaignMetricCreateManyInput = {
  id?: string
  campaignId: string
  roas: number
  recordedAt: Date | string
}

export type CampaignMetricUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  roas?: Prisma.FloatFieldUpdateOperationsInput | number
  recordedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type CampaignMetricUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  campaignId?: Prisma.StringFieldUpdateOperationsInput | string
  roas?: Prisma.FloatFieldUpdateOperationsInput | number
  recordedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type CampaignMetricListRelationFilter = {
  every?: Prisma.CampaignMetricWhereInput
  some?: Prisma.CampaignMetricWhereInput
  none?: Prisma.CampaignMetricWhereInput
}

export type CampaignMetricOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type CampaignMetricCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  campaignId?: Prisma.SortOrder
  roas?: Prisma.SortOrder
  recordedAt?: Prisma.SortOrder
}

export type CampaignMetricAvgOrderByAggregateInput = {
  roas?: Prisma.SortOrder
}

export type CampaignMetricMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  campaignId?: Prisma.SortOrder
  roas?: Prisma.SortOrder
  recordedAt?: Prisma.SortOrder
}

export type CampaignMetricMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  campaignId?: Prisma.SortOrder
  roas?: Prisma.SortOrder
  recordedAt?: Prisma.SortOrder
}

export type CampaignMetricSumOrderByAggregateInput = {
  roas?: Prisma.SortOrder
}

export type CampaignMetricCreateNestedManyWithoutCampaignInput = {
  create?: Prisma.XOR<Prisma.CampaignMetricCreateWithoutCampaignInput, Prisma.CampaignMetricUncheckedCreateWithoutCampaignInput> | Prisma.CampaignMetricCreateWithoutCampaignInput[] | Prisma.CampaignMetricUncheckedCreateWithoutCampaignInput[]
  connectOrCreate?: Prisma.CampaignMetricCreateOrConnectWithoutCampaignInput | Prisma.CampaignMetricCreateOrConnectWithoutCampaignInput[]
  createMany?: Prisma.CampaignMetricCreateManyCampaignInputEnvelope
  connect?: Prisma.CampaignMetricWhereUniqueInput | Prisma.CampaignMetricWhereUniqueInput[]
}

export type CampaignMetricUncheckedCreateNestedManyWithoutCampaignInput = {
  create?: Prisma.XOR<Prisma.CampaignMetricCreateWithoutCampaignInput, Prisma.CampaignMetricUncheckedCreateWithoutCampaignInput> | Prisma.CampaignMetricCreateWithoutCampaignInput[] | Prisma.CampaignMetricUncheckedCreateWithoutCampaignInput[]
  connectOrCreate?: Prisma.CampaignMetricCreateOrConnectWithoutCampaignInput | Prisma.CampaignMetricCreateOrConnectWithoutCampaignInput[]
  createMany?: Prisma.CampaignMetricCreateManyCampaignInputEnvelope
  connect?: Prisma.CampaignMetricWhereUniqueInput | Prisma.CampaignMetricWhereUniqueInput[]
}

export type CampaignMetricUpdateManyWithoutCampaignNestedInput = {
  create?: Prisma.XOR<Prisma.CampaignMetricCreateWithoutCampaignInput, Prisma.CampaignMetricUncheckedCreateWithoutCampaignInput> | Prisma.CampaignMetricCreateWithoutCampaignInput[] | Prisma.CampaignMetricUncheckedCreateWithoutCampaignInput[]
  connectOrCreate?: Prisma.CampaignMetricCreateOrConnectWithoutCampaignInput | Prisma.CampaignMetricCreateOrConnectWithoutCampaignInput[]
  upsert?: Prisma.CampaignMetricUpsertWithWhereUniqueWithoutCampaignInput | Prisma.CampaignMetricUpsertWithWhereUniqueWithoutCampaignInput[]
  createMany?: Prisma.CampaignMetricCreateManyCampaignInputEnvelope
  set?: Prisma.CampaignMetricWhereUniqueInput | Prisma.CampaignMetricWhereUniqueInput[]
  disconnect?: Prisma.CampaignMetricWhereUniqueInput | Prisma.CampaignMetricWhereUniqueInput[]
  delete?: Prisma.CampaignMetricWhereUniqueInput | Prisma.CampaignMetricWhereUniqueInput[]
  connect?: Prisma.CampaignMetricWhereUniqueInput | Prisma.CampaignMetricWhereUniqueInput[]
  update?: Prisma.CampaignMetricUpdateWithWhereUniqueWithoutCampaignInput | Prisma.CampaignMetricUpdateWithWhereUniqueWithoutCampaignInput[]
  updateMany?: Prisma.CampaignMetricUpdateManyWithWhereWithoutCampaignInput | Prisma.CampaignMetricUpdateManyWithWhereWithoutCampaignInput[]
  deleteMany?: Prisma.CampaignMetricScalarWhereInput | Prisma.CampaignMetricScalarWhereInput[]
}

export type CampaignMetricUncheckedUpdateManyWithoutCampaignNestedInput = {
  create?: Prisma.XOR<Prisma.CampaignMetricCreateWithoutCampaignInput, Prisma.CampaignMetricUncheckedCreateWithoutCampaignInput> | Prisma.CampaignMetricCreateWithoutCampaignInput[] | Prisma.CampaignMetricUncheckedCreateWithoutCampaignInput[]
  connectOrCreate?: Prisma.CampaignMetricCreateOrConnectWithoutCampaignInput | Prisma.CampaignMetricCreateOrConnectWithoutCampaignInput[]
  upsert?: Prisma.CampaignMetricUpsertWithWhereUniqueWithoutCampaignInput | Prisma.CampaignMetricUpsertWithWhereUniqueWithoutCampaignInput[]
  createMany?: Prisma.CampaignMetricCreateManyCampaignInputEnvelope
  set?: Prisma.CampaignMetricWhereUniqueInput | Prisma.CampaignMetricWhereUniqueInput[]
  disconnect?: Prisma.CampaignMetricWhereUniqueInput | Prisma.CampaignMetricWhereUniqueInput[]
  delete?: Prisma.CampaignMetricWhereUniqueInput | Prisma.CampaignMetricWhereUniqueInput[]
  connect?: Prisma.CampaignMetricWhereUniqueInput | Prisma.CampaignMetricWhereUniqueInput[]
  update?: Prisma.CampaignMetricUpdateWithWhereUniqueWithoutCampaignInput | Prisma.CampaignMetricUpdateWithWhereUniqueWithoutCampaignInput[]
  updateMany?: Prisma.CampaignMetricUpdateManyWithWhereWithoutCampaignInput | Prisma.CampaignMetricUpdateManyWithWhereWithoutCampaignInput[]
  deleteMany?: Prisma.CampaignMetricScalarWhereInput | Prisma.CampaignMetricScalarWhereInput[]
}

export type FloatFieldUpdateOperationsInput = {
  set?: number
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}

export type DateTimeFieldUpdateOperationsInput = {
  set?: Date | string
}

export type CampaignMetricCreateWithoutCampaignInput = {
  id?: string
  roas: number
  recordedAt: Date | string
}

export type CampaignMetricUncheckedCreateWithoutCampaignInput = {
  id?: string
  roas: number
  recordedAt: Date | string
}

export type CampaignMetricCreateOrConnectWithoutCampaignInput = {
  where: Prisma.CampaignMetricWhereUniqueInput
  create: Prisma.XOR<Prisma.CampaignMetricCreateWithoutCampaignInput, Prisma.CampaignMetricUncheckedCreateWithoutCampaignInput>
}

export type CampaignMetricCreateManyCampaignInputEnvelope = {
  data: Prisma.CampaignMetricCreateManyCampaignInput | Prisma.CampaignMetricCreateManyCampaignInput[]
  skipDuplicates?: boolean
}

export type CampaignMetricUpsertWithWhereUniqueWithoutCampaignInput = {
  where: Prisma.CampaignMetricWhereUniqueInput
  update: Prisma.XOR<Prisma.CampaignMetricUpdateWithoutCampaignInput, Prisma.CampaignMetricUncheckedUpdateWithoutCampaignInput>
  create: Prisma.XOR<Prisma.CampaignMetricCreateWithoutCampaignInput, Prisma.CampaignMetricUncheckedCreateWithoutCampaignInput>
}

export type CampaignMetricUpdateWithWhereUniqueWithoutCampaignInput = {
  where: Prisma.CampaignMetricWhereUniqueInput
  data: Prisma.XOR<Prisma.CampaignMetricUpdateWithoutCampaignInput, Prisma.CampaignMetricUncheckedUpdateWithoutCampaignInput>
}

export type CampaignMetricUpdateManyWithWhereWithoutCampaignInput = {
  where: Prisma.CampaignMetricScalarWhereInput
  data: Prisma.XOR<Prisma.CampaignMetricUpdateManyMutationInput, Prisma.CampaignMetricUncheckedUpdateManyWithoutCampaignInput>
}

export type CampaignMetricScalarWhereInput = {
  AND?: Prisma.CampaignMetricScalarWhereInput | Prisma.CampaignMetricScalarWhereInput[]
  OR?: Prisma.CampaignMetricScalarWhereInput[]
  NOT?: Prisma.CampaignMetricScalarWhereInput | Prisma.CampaignMetricScalarWhereInput[]
  id?: Prisma.StringFilter<"CampaignMetric"> | string
  campaignId?: Prisma.StringFilter<"CampaignMetric"> | string
  roas?: Prisma.FloatFilter<"CampaignMetric"> | number
  recordedAt?: Prisma.DateTimeFilter<"CampaignMetric"> | Date | string
}

export type CampaignMetricCreateManyCampaignInput = {
  id?: string
  roas: number
  recordedAt: Date | string
}

export type CampaignMetricUpdateWithoutCampaignInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  roas?: Prisma.FloatFieldUpdateOperationsInput | number
  recordedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type CampaignMetricUncheckedUpdateWithoutCampaignInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  roas?: Prisma.FloatFieldUpdateOperationsInput | number
  recordedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type CampaignMetricUncheckedUpdateManyWithoutCampaignInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  roas?: Prisma.FloatFieldUpdateOperationsInput | number
  recordedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type CampaignMetricSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  campaignId?: boolean
  roas?: boolean
  recordedAt?: boolean
  campaign?: boolean | Prisma.CampaignDefaultArgs<ExtArgs>
}, ExtArgs["result"]["campaignMetric"]>

export type CampaignMetricSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  campaignId?: boolean
  roas?: boolean
  recordedAt?: boolean
  campaign?: boolean | Prisma.CampaignDefaultArgs<ExtArgs>
}, ExtArgs["result"]["campaignMetric"]>

export type CampaignMetricSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  campaignId?: boolean
  roas?: boolean
  recordedAt?: boolean
  campaign?: boolean | Prisma.CampaignDefaultArgs<ExtArgs>
}, ExtArgs["result"]["campaignMetric"]>

export type CampaignMetricSelectScalar = {
  id?: boolean
  campaignId?: boolean
  roas?: boolean
  recordedAt?: boolean
}

export type CampaignMetricOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "campaignId" | "roas" | "recordedAt", ExtArgs["result"]["campaignMetric"]>
export type CampaignMetricInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  campaign?: boolean | Prisma.CampaignDefaultArgs<ExtArgs>
}
export type CampaignMetricIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  campaign?: boolean | Prisma.CampaignDefaultArgs<ExtArgs>
}
export type CampaignMetricIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  campaign?: boolean | Prisma.CampaignDefaultArgs<ExtArgs>
}

export type $CampaignMetricPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "CampaignMetric"
  objects: {
    campaign: Prisma.$CampaignPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    campaignId: string
    roas: number
    recordedAt: Date
  }, ExtArgs["result"]["campaignMetric"]>
  composites: {}
}

export type CampaignMetricGetPayload<S extends boolean | null | undefined | CampaignMetricDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$CampaignMetricPayload, S>

export type CampaignMetricCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<CampaignMetricFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: CampaignMetricCountAggregateInputType | true
  }

export interface CampaignMetricDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['CampaignMetric'], meta: { name: 'CampaignMetric' } }
  /**
   * Find zero or one CampaignMetric that matches the filter.
   * @param {CampaignMetricFindUniqueArgs} args - Arguments to find a CampaignMetric
   * @example
   * // Get one CampaignMetric
   * const campaignMetric = await prisma.campaignMetric.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends CampaignMetricFindUniqueArgs>(args: Prisma.SelectSubset<T, CampaignMetricFindUniqueArgs<ExtArgs>>): Prisma.Prisma__CampaignMetricClient<runtime.Types.Result.GetResult<Prisma.$CampaignMetricPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one CampaignMetric that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {CampaignMetricFindUniqueOrThrowArgs} args - Arguments to find a CampaignMetric
   * @example
   * // Get one CampaignMetric
   * const campaignMetric = await prisma.campaignMetric.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends CampaignMetricFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, CampaignMetricFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__CampaignMetricClient<runtime.Types.Result.GetResult<Prisma.$CampaignMetricPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first CampaignMetric that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CampaignMetricFindFirstArgs} args - Arguments to find a CampaignMetric
   * @example
   * // Get one CampaignMetric
   * const campaignMetric = await prisma.campaignMetric.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends CampaignMetricFindFirstArgs>(args?: Prisma.SelectSubset<T, CampaignMetricFindFirstArgs<ExtArgs>>): Prisma.Prisma__CampaignMetricClient<runtime.Types.Result.GetResult<Prisma.$CampaignMetricPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first CampaignMetric that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CampaignMetricFindFirstOrThrowArgs} args - Arguments to find a CampaignMetric
   * @example
   * // Get one CampaignMetric
   * const campaignMetric = await prisma.campaignMetric.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends CampaignMetricFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, CampaignMetricFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__CampaignMetricClient<runtime.Types.Result.GetResult<Prisma.$CampaignMetricPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more CampaignMetrics that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CampaignMetricFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all CampaignMetrics
   * const campaignMetrics = await prisma.campaignMetric.findMany()
   * 
   * // Get first 10 CampaignMetrics
   * const campaignMetrics = await prisma.campaignMetric.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const campaignMetricWithIdOnly = await prisma.campaignMetric.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends CampaignMetricFindManyArgs>(args?: Prisma.SelectSubset<T, CampaignMetricFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CampaignMetricPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a CampaignMetric.
   * @param {CampaignMetricCreateArgs} args - Arguments to create a CampaignMetric.
   * @example
   * // Create one CampaignMetric
   * const CampaignMetric = await prisma.campaignMetric.create({
   *   data: {
   *     // ... data to create a CampaignMetric
   *   }
   * })
   * 
   */
  create<T extends CampaignMetricCreateArgs>(args: Prisma.SelectSubset<T, CampaignMetricCreateArgs<ExtArgs>>): Prisma.Prisma__CampaignMetricClient<runtime.Types.Result.GetResult<Prisma.$CampaignMetricPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many CampaignMetrics.
   * @param {CampaignMetricCreateManyArgs} args - Arguments to create many CampaignMetrics.
   * @example
   * // Create many CampaignMetrics
   * const campaignMetric = await prisma.campaignMetric.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends CampaignMetricCreateManyArgs>(args?: Prisma.SelectSubset<T, CampaignMetricCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many CampaignMetrics and returns the data saved in the database.
   * @param {CampaignMetricCreateManyAndReturnArgs} args - Arguments to create many CampaignMetrics.
   * @example
   * // Create many CampaignMetrics
   * const campaignMetric = await prisma.campaignMetric.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many CampaignMetrics and only return the `id`
   * const campaignMetricWithIdOnly = await prisma.campaignMetric.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends CampaignMetricCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, CampaignMetricCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CampaignMetricPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a CampaignMetric.
   * @param {CampaignMetricDeleteArgs} args - Arguments to delete one CampaignMetric.
   * @example
   * // Delete one CampaignMetric
   * const CampaignMetric = await prisma.campaignMetric.delete({
   *   where: {
   *     // ... filter to delete one CampaignMetric
   *   }
   * })
   * 
   */
  delete<T extends CampaignMetricDeleteArgs>(args: Prisma.SelectSubset<T, CampaignMetricDeleteArgs<ExtArgs>>): Prisma.Prisma__CampaignMetricClient<runtime.Types.Result.GetResult<Prisma.$CampaignMetricPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one CampaignMetric.
   * @param {CampaignMetricUpdateArgs} args - Arguments to update one CampaignMetric.
   * @example
   * // Update one CampaignMetric
   * const campaignMetric = await prisma.campaignMetric.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends CampaignMetricUpdateArgs>(args: Prisma.SelectSubset<T, CampaignMetricUpdateArgs<ExtArgs>>): Prisma.Prisma__CampaignMetricClient<runtime.Types.Result.GetResult<Prisma.$CampaignMetricPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more CampaignMetrics.
   * @param {CampaignMetricDeleteManyArgs} args - Arguments to filter CampaignMetrics to delete.
   * @example
   * // Delete a few CampaignMetrics
   * const { count } = await prisma.campaignMetric.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends CampaignMetricDeleteManyArgs>(args?: Prisma.SelectSubset<T, CampaignMetricDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more CampaignMetrics.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CampaignMetricUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many CampaignMetrics
   * const campaignMetric = await prisma.campaignMetric.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends CampaignMetricUpdateManyArgs>(args: Prisma.SelectSubset<T, CampaignMetricUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more CampaignMetrics and returns the data updated in the database.
   * @param {CampaignMetricUpdateManyAndReturnArgs} args - Arguments to update many CampaignMetrics.
   * @example
   * // Update many CampaignMetrics
   * const campaignMetric = await prisma.campaignMetric.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more CampaignMetrics and only return the `id`
   * const campaignMetricWithIdOnly = await prisma.campaignMetric.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends CampaignMetricUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, CampaignMetricUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CampaignMetricPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one CampaignMetric.
   * @param {CampaignMetricUpsertArgs} args - Arguments to update or create a CampaignMetric.
   * @example
   * // Update or create a CampaignMetric
   * const campaignMetric = await prisma.campaignMetric.upsert({
   *   create: {
   *     // ... data to create a CampaignMetric
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the CampaignMetric we want to update
   *   }
   * })
   */
  upsert<T extends CampaignMetricUpsertArgs>(args: Prisma.SelectSubset<T, CampaignMetricUpsertArgs<ExtArgs>>): Prisma.Prisma__CampaignMetricClient<runtime.Types.Result.GetResult<Prisma.$CampaignMetricPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of CampaignMetrics.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CampaignMetricCountArgs} args - Arguments to filter CampaignMetrics to count.
   * @example
   * // Count the number of CampaignMetrics
   * const count = await prisma.campaignMetric.count({
   *   where: {
   *     // ... the filter for the CampaignMetrics we want to count
   *   }
   * })
  **/
  count<T extends CampaignMetricCountArgs>(
    args?: Prisma.Subset<T, CampaignMetricCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], CampaignMetricCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a CampaignMetric.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CampaignMetricAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends CampaignMetricAggregateArgs>(args: Prisma.Subset<T, CampaignMetricAggregateArgs>): Prisma.PrismaPromise<GetCampaignMetricAggregateType<T>>

  /**
   * Group by CampaignMetric.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CampaignMetricGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends CampaignMetricGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: CampaignMetricGroupByArgs['orderBy'] }
      : { orderBy?: CampaignMetricGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, CampaignMetricGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetCampaignMetricGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the CampaignMetric model
 */
readonly fields: CampaignMetricFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for CampaignMetric.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__CampaignMetricClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  campaign<T extends Prisma.CampaignDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.CampaignDefaultArgs<ExtArgs>>): Prisma.Prisma__CampaignClient<runtime.Types.Result.GetResult<Prisma.$CampaignPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the CampaignMetric model
 */
export interface CampaignMetricFieldRefs {
  readonly id: Prisma.FieldRef<"CampaignMetric", 'String'>
  readonly campaignId: Prisma.FieldRef<"CampaignMetric", 'String'>
  readonly roas: Prisma.FieldRef<"CampaignMetric", 'Float'>
  readonly recordedAt: Prisma.FieldRef<"CampaignMetric", 'DateTime'>
}
    

// Custom InputTypes
/**
 * CampaignMetric findUnique
 */
export type CampaignMetricFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CampaignMetric
   */
  select?: Prisma.CampaignMetricSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CampaignMetric
   */
  omit?: Prisma.CampaignMetricOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CampaignMetricInclude<ExtArgs> | null
  /**
   * Filter, which CampaignMetric to fetch.
   */
  where: Prisma.CampaignMetricWhereUniqueInput
}

/**
 * CampaignMetric findUniqueOrThrow
 */
export type CampaignMetricFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CampaignMetric
   */
  select?: Prisma.CampaignMetricSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CampaignMetric
   */
  omit?: Prisma.CampaignMetricOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CampaignMetricInclude<ExtArgs> | null
  /**
   * Filter, which CampaignMetric to fetch.
   */
  where: Prisma.CampaignMetricWhereUniqueInput
}

/**
 * CampaignMetric findFirst
 */
export type CampaignMetricFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CampaignMetric
   */
  select?: Prisma.CampaignMetricSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CampaignMetric
   */
  omit?: Prisma.CampaignMetricOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CampaignMetricInclude<ExtArgs> | null
  /**
   * Filter, which CampaignMetric to fetch.
   */
  where?: Prisma.CampaignMetricWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of CampaignMetrics to fetch.
   */
  orderBy?: Prisma.CampaignMetricOrderByWithRelationInput | Prisma.CampaignMetricOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for CampaignMetrics.
   */
  cursor?: Prisma.CampaignMetricWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` CampaignMetrics from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` CampaignMetrics.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of CampaignMetrics.
   */
  distinct?: Prisma.CampaignMetricScalarFieldEnum | Prisma.CampaignMetricScalarFieldEnum[]
}

/**
 * CampaignMetric findFirstOrThrow
 */
export type CampaignMetricFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CampaignMetric
   */
  select?: Prisma.CampaignMetricSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CampaignMetric
   */
  omit?: Prisma.CampaignMetricOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CampaignMetricInclude<ExtArgs> | null
  /**
   * Filter, which CampaignMetric to fetch.
   */
  where?: Prisma.CampaignMetricWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of CampaignMetrics to fetch.
   */
  orderBy?: Prisma.CampaignMetricOrderByWithRelationInput | Prisma.CampaignMetricOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for CampaignMetrics.
   */
  cursor?: Prisma.CampaignMetricWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` CampaignMetrics from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` CampaignMetrics.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of CampaignMetrics.
   */
  distinct?: Prisma.CampaignMetricScalarFieldEnum | Prisma.CampaignMetricScalarFieldEnum[]
}

/**
 * CampaignMetric findMany
 */
export type CampaignMetricFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CampaignMetric
   */
  select?: Prisma.CampaignMetricSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CampaignMetric
   */
  omit?: Prisma.CampaignMetricOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CampaignMetricInclude<ExtArgs> | null
  /**
   * Filter, which CampaignMetrics to fetch.
   */
  where?: Prisma.CampaignMetricWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of CampaignMetrics to fetch.
   */
  orderBy?: Prisma.CampaignMetricOrderByWithRelationInput | Prisma.CampaignMetricOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing CampaignMetrics.
   */
  cursor?: Prisma.CampaignMetricWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` CampaignMetrics from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` CampaignMetrics.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of CampaignMetrics.
   */
  distinct?: Prisma.CampaignMetricScalarFieldEnum | Prisma.CampaignMetricScalarFieldEnum[]
}

/**
 * CampaignMetric create
 */
export type CampaignMetricCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CampaignMetric
   */
  select?: Prisma.CampaignMetricSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CampaignMetric
   */
  omit?: Prisma.CampaignMetricOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CampaignMetricInclude<ExtArgs> | null
  /**
   * The data needed to create a CampaignMetric.
   */
  data: Prisma.XOR<Prisma.CampaignMetricCreateInput, Prisma.CampaignMetricUncheckedCreateInput>
}

/**
 * CampaignMetric createMany
 */
export type CampaignMetricCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many CampaignMetrics.
   */
  data: Prisma.CampaignMetricCreateManyInput | Prisma.CampaignMetricCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * CampaignMetric createManyAndReturn
 */
export type CampaignMetricCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CampaignMetric
   */
  select?: Prisma.CampaignMetricSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the CampaignMetric
   */
  omit?: Prisma.CampaignMetricOmit<ExtArgs> | null
  /**
   * The data used to create many CampaignMetrics.
   */
  data: Prisma.CampaignMetricCreateManyInput | Prisma.CampaignMetricCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CampaignMetricIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * CampaignMetric update
 */
export type CampaignMetricUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CampaignMetric
   */
  select?: Prisma.CampaignMetricSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CampaignMetric
   */
  omit?: Prisma.CampaignMetricOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CampaignMetricInclude<ExtArgs> | null
  /**
   * The data needed to update a CampaignMetric.
   */
  data: Prisma.XOR<Prisma.CampaignMetricUpdateInput, Prisma.CampaignMetricUncheckedUpdateInput>
  /**
   * Choose, which CampaignMetric to update.
   */
  where: Prisma.CampaignMetricWhereUniqueInput
}

/**
 * CampaignMetric updateMany
 */
export type CampaignMetricUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update CampaignMetrics.
   */
  data: Prisma.XOR<Prisma.CampaignMetricUpdateManyMutationInput, Prisma.CampaignMetricUncheckedUpdateManyInput>
  /**
   * Filter which CampaignMetrics to update
   */
  where?: Prisma.CampaignMetricWhereInput
  /**
   * Limit how many CampaignMetrics to update.
   */
  limit?: number
}

/**
 * CampaignMetric updateManyAndReturn
 */
export type CampaignMetricUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CampaignMetric
   */
  select?: Prisma.CampaignMetricSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the CampaignMetric
   */
  omit?: Prisma.CampaignMetricOmit<ExtArgs> | null
  /**
   * The data used to update CampaignMetrics.
   */
  data: Prisma.XOR<Prisma.CampaignMetricUpdateManyMutationInput, Prisma.CampaignMetricUncheckedUpdateManyInput>
  /**
   * Filter which CampaignMetrics to update
   */
  where?: Prisma.CampaignMetricWhereInput
  /**
   * Limit how many CampaignMetrics to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CampaignMetricIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * CampaignMetric upsert
 */
export type CampaignMetricUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CampaignMetric
   */
  select?: Prisma.CampaignMetricSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CampaignMetric
   */
  omit?: Prisma.CampaignMetricOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CampaignMetricInclude<ExtArgs> | null
  /**
   * The filter to search for the CampaignMetric to update in case it exists.
   */
  where: Prisma.CampaignMetricWhereUniqueInput
  /**
   * In case the CampaignMetric found by the `where` argument doesn't exist, create a new CampaignMetric with this data.
   */
  create: Prisma.XOR<Prisma.CampaignMetricCreateInput, Prisma.CampaignMetricUncheckedCreateInput>
  /**
   * In case the CampaignMetric was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.CampaignMetricUpdateInput, Prisma.CampaignMetricUncheckedUpdateInput>
}

/**
 * CampaignMetric delete
 */
export type CampaignMetricDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CampaignMetric
   */
  select?: Prisma.CampaignMetricSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CampaignMetric
   */
  omit?: Prisma.CampaignMetricOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CampaignMetricInclude<ExtArgs> | null
  /**
   * Filter which CampaignMetric to delete.
   */
  where: Prisma.CampaignMetricWhereUniqueInput
}

/**
 * CampaignMetric deleteMany
 */
export type CampaignMetricDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which CampaignMetrics to delete
   */
  where?: Prisma.CampaignMetricWhereInput
  /**
   * Limit how many CampaignMetrics to delete.
   */
  limit?: number
}

/**
 * CampaignMetric without action
 */
export type CampaignMetricDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CampaignMetric
   */
  select?: Prisma.CampaignMetricSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CampaignMetric
   */
  omit?: Prisma.CampaignMetricOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CampaignMetricInclude<ExtArgs> | null
}
